#TPCH9:ver1.0

SELECT NATION.NAME, EXTRACT_YEAR(ORDERS.ORDERDATE), SUM((LINEITEM.EXTENDEDPRICE*(1.0-LINEITEM.DISCOUNT))-(PARTSUPP.SUPPLYCOST * LINEITEM.QUANTITY)) FROM PART
inner join LINEITEM on PART.PARTKEY = LINEITEM.PARTKEY
inner join PARTSUPP on PARTSUPP.PARTKEY = LINEITEM.PARTKEY AND PARTSUPP.SUPPKEY = LINEITEM.SUPPKEY
inner join ORDERS on LINEITEM.ORDERKEY = ORDERS.ORDERKEY
inner join SUPPLIER on SUPPLIER.SUPPKEY = LINEITEM.SUPPKEY
inner join NATION on NATION.NATIONKEY = SUPPLIER.NATIONKEY
WHERE PART.NAME LIKE '%green%'
GROUP BY NATION.NAME, ORDERS.ORDERDATE
