#TPCH10:ver1.0

SELECT CUSTOMER.CUSTKEY, CUSTOMER.NAME, SUM(LINEITEM.EXTENDEDPRICE * (1.0 - LINEITEM.DISCOUNT)), CUSTOMER.ACCTBAL, NATION.NAME, CUSTOMER.ADDRESS, CUSTOMER.PHONE, CUSTOMER.COMMENT FROM CUSTOMER
inner join ORDERS on CUSTOMER.CUSTKEY = ORDERS.CUSTKEY
inner join NATION on NATION.NATIONKEY = CUSTOMER.NATIONKEY
inner join LINEITEM on LINEITEM.ORDERKEY = ORDERS.ORDERKEY
WHERE ORDERS.ORDERDATE >= {d '1993-10-01'} AND ORDERS.ORDERDATE < {d '1994-01-01'}
AND LINEITEM.RETURNFLAG = 'R'
GROUP BY CUSTOMER.CUSTKEY, CUSTOMER.NAME, NATION.NAME, CUSTOMER.ADDRESS, CUSTOMER.PHONE, CUSTOMER.COMMENT

