/* Generated By:JavaCC: Do not edit this line. SchemaParserTokenManager.java */
/** Schema + cardinality information extractor. */
package sql.schema.parser;

/** Token Manager. */
public class SchemaParserTokenManager implements SchemaParserConstants {

	/** Debug output. */
	public java.io.PrintStream debugStream = System.out;

	static final int[] jjnextStates = { 18, 20, };

	/** Token literal values. */
	public static final String[] jjstrLiteralImages = { "", null, null, null, null, "\50", "\51",
			"\133", "\135", "\73", "\54", "\75", null, null, null, null, null, null, null, null,
			null, };

	/** Lexer state names. */
	public static final String[] lexStateNames = { "DEFAULT", };

	static final long[] jjtoToken = { 0x1fffe1L, };

	static final long[] jjtoSkip = { 0x1eL, };

	protected SimpleCharStream input_stream;

	private final int[] jjrounds = new int[21];

	private final int[] jjstateSet = new int[42];

	protected char curChar;

	int curLexState = 0;

	int defaultLexState = 0;

	int jjnewStateCnt;

	int jjround;

	int jjmatchedPos;

	int jjmatchedKind;

	/** Constructor. */
	public SchemaParserTokenManager(SimpleCharStream stream) {
		if (SimpleCharStream.staticFlag)
			throw new Error(
					"ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
		input_stream = stream;
	}

	/** Constructor. */
	public SchemaParserTokenManager(SimpleCharStream stream, int lexState) {
		this(stream);
		SwitchTo(lexState);
	}

	/** Get the next Token. */
	public Token getNextToken() {
		Token matchedToken;
		int curPos = 0;

		EOFLoop: for (;;) {
			try {
				curChar = input_stream.BeginToken();
			} catch (final java.io.IOException e) {
				jjmatchedKind = 0;
				matchedToken = jjFillToken();
				return matchedToken;
			}

			try {
				input_stream.backup(0);
				while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
					curChar = input_stream.BeginToken();
			} catch (final java.io.IOException e1) {
				continue EOFLoop;
			}
			jjmatchedKind = 0x7fffffff;
			jjmatchedPos = 0;
			curPos = jjMoveStringLiteralDfa0_0();
			if (jjmatchedKind != 0x7fffffff) {
				if (jjmatchedPos + 1 < curPos)
					input_stream.backup(curPos - jjmatchedPos - 1);
				if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
					matchedToken = jjFillToken();
					return matchedToken;
				} else
					continue EOFLoop;
			}
			int error_line = input_stream.getEndLine();
			int error_column = input_stream.getEndColumn();
			String error_after = null;
			boolean EOFSeen = false;
			try {
				input_stream.readChar();
				input_stream.backup(1);
			} catch (final java.io.IOException e1) {
				EOFSeen = true;
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
				if (curChar == '\n' || curChar == '\r') {
					error_line++;
					error_column = 0;
				} else
					error_column++;
			}
			if (!EOFSeen) {
				input_stream.backup(1);
				error_after = curPos <= 1 ? "" : input_stream.GetImage();
			}
			throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after,
					curChar, TokenMgrError.LEXICAL_ERROR);
		}
	}

	private void jjAddStates(int start, int end) {
		do
			jjstateSet[jjnewStateCnt++] = jjnextStates[start];
		while (start++ != end);
	}

	private void jjCheckNAdd(int state) {
		if (jjrounds[state] != jjround) {
			jjstateSet[jjnewStateCnt++] = state;
			jjrounds[state] = jjround;
		}
	}

	protected Token jjFillToken() {
		final Token t;
		final String curTokenImage;
		final int beginLine;
		final int endLine;
		final int beginColumn;
		final int endColumn;
		final String im = jjstrLiteralImages[jjmatchedKind];
		curTokenImage = (im == null) ? input_stream.GetImage() : im;
		beginLine = input_stream.getBeginLine();
		beginColumn = input_stream.getBeginColumn();
		endLine = input_stream.getEndLine();
		endColumn = input_stream.getEndColumn();
		t = Token.newToken(jjmatchedKind, curTokenImage);

		t.beginLine = beginLine;
		t.endLine = endLine;
		t.beginColumn = beginColumn;
		t.endColumn = endColumn;

		return t;
	}

	private int jjMoveNfa_0(int startState, int curPos) {
		int startsAt = 0;
		jjnewStateCnt = 21;
		int i = 1;
		jjstateSet[0] = startState;
		int kind = 0x7fffffff;
		for (;;) {
			if (++jjround == 0x7fffffff)
				ReInitRounds();
			if (curChar < 64) {
				final long l = 1L << curChar;
				do
					switch (jjstateSet[--i]) {
					case 18:
						if ((0x3ff600000000000L & l) != 0L) {
							if (kind > 20)
								kind = 20;
							jjCheckNAdd(12);
						}
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 19)
								kind = 19;
							jjCheckNAdd(11);
						}
						break;
					case 3:
						if ((0x3ff600000000000L & l) != 0L) {
							if (kind > 20)
								kind = 20;
							jjCheckNAdd(12);
						}
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 18)
								kind = 18;
							jjCheckNAdd(9);
						}
						break;
					case 21:
						if ((0x3ff600000000000L & l) != 0L) {
							if (kind > 20)
								kind = 20;
							jjCheckNAdd(12);
						}
						if ((0x3ff000000000000L & l) != 0L) {
							if (kind > 19)
								kind = 19;
							jjCheckNAdd(11);
						}
						break;
					case 9:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 18)
							kind = 18;
						jjCheckNAdd(9);
						break;
					case 11:
						if ((0x3ff000000000000L & l) == 0L)
							break;
						if (kind > 19)
							kind = 19;
						jjCheckNAdd(11);
						break;
					case 12:
						if ((0x3ff600000000000L & l) == 0L)
							break;
						if (kind > 20)
							kind = 20;
						jjCheckNAdd(12);
						break;
					default:
						break;
					}
				while (i != startsAt);
			} else if (curChar < 128) {
				final long l = 1L << (curChar & 077);
				do
					switch (jjstateSet[--i]) {
					case 18:
						if ((0x7fffffe87fffffeL & l) != 0L) {
							if (kind > 20)
								kind = 20;
							jjCheckNAdd(12);
						}
						if ((0x7fffffe87fffffeL & l) != 0L) {
							if (kind > 19)
								kind = 19;
							jjCheckNAdd(11);
						}
						if ((0x200000002L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 19;
						else if ((0x800000008000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 17;
						break;
					case 3:
						if ((0x7fffffe87fffffeL & l) != 0L) {
							if (kind > 20)
								kind = 20;
							jjCheckNAdd(12);
						}
						if ((0x7fffffe87fffffeL & l) != 0L)
							jjCheckNAdd(11);
						if ((0x1000000010L & l) != 0L)
							jjAddStates(0, 1);
						else if ((0x8000000080000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 7;
						else if ((0x100000001000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 2;
						break;
					case 21:
						if ((0x7fffffe87fffffeL & l) != 0L) {
							if (kind > 20)
								kind = 20;
							jjCheckNAdd(12);
						}
						if ((0x7fffffe87fffffeL & l) != 0L) {
							if (kind > 19)
								kind = 19;
							jjCheckNAdd(11);
						}
						break;
					case 0:
						if ((0x8000000080L & l) != 0L && kind > 17)
							kind = 17;
						break;
					case 1:
					case 4:
						if ((0x400000004000L & l) != 0L)
							jjCheckNAdd(0);
						break;
					case 2:
						if ((0x800000008000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 1;
						break;
					case 5:
						if ((0x20000000200L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 4;
						break;
					case 6:
						if ((0x4000000040000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 5;
						break;
					case 7:
						if ((0x10000000100000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 6;
						break;
					case 8:
						if ((0x8000000080000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 7;
						break;
					case 10:
						if ((0x7fffffe87fffffeL & l) != 0L)
							jjCheckNAdd(11);
						break;
					case 11:
						if ((0x7fffffe87fffffeL & l) == 0L)
							break;
						if (kind > 19)
							kind = 19;
						jjCheckNAdd(11);
						break;
					case 12:
						if ((0x7fffffe87fffffeL & l) == 0L)
							break;
						if (kind > 20)
							kind = 20;
						jjCheckNAdd(12);
						break;
					case 13:
						if ((0x1000000010L & l) != 0L)
							jjAddStates(0, 1);
						break;
					case 14:
						if ((0x2000000020L & l) != 0L && kind > 17)
							kind = 17;
						break;
					case 15:
						if ((0x100000001000L & l) != 0L)
							jjCheckNAdd(14);
						break;
					case 16:
						if ((0x400000004L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 15;
						break;
					case 17:
						if ((0x20000000200000L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 16;
						break;
					case 19:
						if ((0x10000000100000L & l) != 0L)
							jjCheckNAdd(14);
						break;
					case 20:
						if ((0x200000002L & l) != 0L)
							jjstateSet[jjnewStateCnt++] = 19;
						break;
					default:
						break;
					}
				while (i != startsAt);
			} else {
				do
					switch (jjstateSet[--i]) {
					default:
						break;
					}
				while (i != startsAt);
			}
			if (kind != 0x7fffffff) {
				jjmatchedKind = kind;
				jjmatchedPos = curPos;
				kind = 0x7fffffff;
			}
			++curPos;
			if ((i = jjnewStateCnt) == (startsAt = 21 - (jjnewStateCnt = startsAt)))
				return curPos;
			try {
				curChar = input_stream.readChar();
			} catch (final java.io.IOException e) {
				return curPos;
			}
		}
	}

	private int jjMoveStringLiteralDfa0_0() {
		switch (curChar) {
		case 40:
			return jjStopAtPos(0, 5);
		case 41:
			return jjStopAtPos(0, 6);
		case 44:
			return jjStopAtPos(0, 10);
		case 58:
			return jjMoveStringLiteralDfa1_0(0x1000L);
		case 59:
			return jjStopAtPos(0, 9);
		case 61:
			return jjStopAtPos(0, 11);
		case 91:
			return jjStopAtPos(0, 7);
		case 93:
			return jjStopAtPos(0, 8);
		case 68:
		case 100:
			return jjMoveStringLiteralDfa1_0(0x10000L);
		case 77:
		case 109:
			return jjMoveStringLiteralDfa1_0(0x6000L);
		case 84:
		case 116:
			return jjMoveStringLiteralDfa1_0(0x8000L);
		default:
			return jjMoveNfa_0(3, 0);
		}
	}

	private int jjMoveStringLiteralDfa1_0(long active0) {
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(0, active0);
			return 1;
		}
		switch (curChar) {
		case 65:
		case 97:
			return jjMoveStringLiteralDfa2_0(active0, 0xa000L);
		case 73:
		case 105:
			return jjMoveStringLiteralDfa2_0(active0, 0x14000L);
		case 83:
		case 115:
			if ((active0 & 0x1000L) != 0L)
				return jjStopAtPos(1, 12);
			break;
		default:
			break;
		}
		return jjStartNfa_0(0, active0);
	}

	private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(0, old0);
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(1, active0);
			return 2;
		}
		switch (curChar) {
		case 66:
		case 98:
			return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
		case 78:
		case 110:
			if ((active0 & 0x4000L) != 0L)
				return jjStartNfaWithStates_0(2, 14, 21);
			break;
		case 83:
		case 115:
			return jjMoveStringLiteralDfa3_0(active0, 0x10000L);
		case 88:
		case 120:
			if ((active0 & 0x2000L) != 0L)
				return jjStartNfaWithStates_0(2, 13, 21);
			break;
		default:
			break;
		}
		return jjStartNfa_0(1, active0);
	}

	private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(1, old0);
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(2, active0);
			return 3;
		}
		switch (curChar) {
		case 76:
		case 108:
			return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
		case 84:
		case 116:
			return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
		default:
			break;
		}
		return jjStartNfa_0(2, active0);
	}

	private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(2, old0);
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(3, active0);
			return 4;
		}
		switch (curChar) {
		case 69:
		case 101:
			if ((active0 & 0x8000L) != 0L)
				return jjStartNfaWithStates_0(4, 15, 21);
			break;
		case 73:
		case 105:
			return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
		default:
			break;
		}
		return jjStartNfa_0(3, active0);
	}

	private int jjMoveStringLiteralDfa5_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(3, old0);
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(4, active0);
			return 5;
		}
		switch (curChar) {
		case 78:
		case 110:
			return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
		default:
			break;
		}
		return jjStartNfa_0(4, active0);
	}

	private int jjMoveStringLiteralDfa6_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(4, old0);
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(5, active0);
			return 6;
		}
		switch (curChar) {
		case 67:
		case 99:
			return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
		default:
			break;
		}
		return jjStartNfa_0(5, active0);
	}

	private int jjMoveStringLiteralDfa7_0(long old0, long active0) {
		if (((active0 &= old0)) == 0L)
			return jjStartNfa_0(5, old0);
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			jjStopStringLiteralDfa_0(6, active0);
			return 7;
		}
		switch (curChar) {
		case 84:
		case 116:
			if ((active0 & 0x10000L) != 0L)
				return jjStartNfaWithStates_0(7, 16, 21);
			break;
		default:
			break;
		}
		return jjStartNfa_0(6, active0);
	}

	private final int jjStartNfa_0(int pos, long active0) {
		return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
	}

	private int jjStartNfaWithStates_0(int pos, int kind, int state) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		try {
			curChar = input_stream.readChar();
		} catch (final java.io.IOException e) {
			return pos + 1;
		}
		return jjMoveNfa_0(state, pos + 1);
	}

	private int jjStopAtPos(int pos, int kind) {
		jjmatchedKind = kind;
		jjmatchedPos = pos;
		return pos + 1;
	}

	private final int jjStopStringLiteralDfa_0(int pos, long active0) {
		switch (pos) {
		case 0:
			if ((active0 & 0x10000L) != 0L) {
				jjmatchedKind = 20;
				return 18;
			}
			if ((active0 & 0xe000L) != 0L) {
				jjmatchedKind = 20;
				return 21;
			}
			return -1;
		case 1:
			if ((active0 & 0x1e000L) != 0L) {
				jjmatchedKind = 19;
				jjmatchedPos = 1;
				return 21;
			}
			return -1;
		case 2:
			if ((active0 & 0x18000L) != 0L) {
				jjmatchedKind = 19;
				jjmatchedPos = 2;
				return 21;
			}
			if ((active0 & 0x6000L) != 0L)
				return 21;
			return -1;
		case 3:
			if ((active0 & 0x18000L) != 0L) {
				jjmatchedKind = 19;
				jjmatchedPos = 3;
				return 21;
			}
			return -1;
		case 4:
			if ((active0 & 0x10000L) != 0L) {
				jjmatchedKind = 19;
				jjmatchedPos = 4;
				return 21;
			}
			if ((active0 & 0x8000L) != 0L)
				return 21;
			return -1;
		case 5:
			if ((active0 & 0x10000L) != 0L) {
				jjmatchedKind = 19;
				jjmatchedPos = 5;
				return 21;
			}
			return -1;
		case 6:
			if ((active0 & 0x10000L) != 0L) {
				jjmatchedKind = 19;
				jjmatchedPos = 6;
				return 21;
			}
			return -1;
		default:
			return -1;
		}
	}

	/** Reinitialise parser. */
	public void ReInit(SimpleCharStream stream) {
		jjmatchedPos = jjnewStateCnt = 0;
		curLexState = defaultLexState;
		input_stream = stream;
		ReInitRounds();
	}

	/** Reinitialise parser. */
	public void ReInit(SimpleCharStream stream, int lexState) {
		ReInit(stream);
		SwitchTo(lexState);
	}

	private void ReInitRounds() {
		int i;
		jjround = 0x80000001;
		for (i = 21; i-- > 0;)
			jjrounds[i] = 0x80000000;
	}

	/** Set debug output. */
	public void setDebugStream(java.io.PrintStream ds) {
		debugStream = ds;
	}

	/** Switch to specified lex state. */
	public void SwitchTo(int lexState) {
		if (lexState >= 1 || lexState < 0)
			throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState
					+ ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
		else
			curLexState = lexState;
	}

}
