SELECT ORDERS.ORDERPRIORITY, COUNT(DISTINCT(LINEITEM.ORDERKEY))
FROM LINEITEM inner join ORDERS on LINEITEM.ORDERKEY = ORDERS.ORDERKEY
WHERE ORDERS.ORDERDATE >= {d '1993-07-01'} AND ORDERS.ORDERDATE < {d '1993-10-01'}
AND (LINEITEM.COMMITDATE < LINEITEM.RECEIPTDATE)
