SELECT SUM(LINEITEM.EXTENDEDPRICE * (1.0 - LINEITEM.DISCOUNT))
FROM LINEITEM INNER JOIN PART ON LINEITEM.PARTKEY = PART.PARTKEY
WHERE (PART.CONTAINER = 'SM CASE') OR (PART.CONTAINER = 'SM BOX') OR 
(PART.CONTAINER = 'SM PACK') OR (PART.CONTAINER ='SM PKG')
