SELECT SUM(LINEITEM.EXTENDEDPRICE * (1 - LINEITEM.DISCOUNT)) FROM LINEITEM INNER
JOIN PART ON PART.PARTKEY = LINEITEM.PARTKEY
WHERE (PART.CONTAINER = 'SM CASE') OR (PART.CONTAINER = 'SM BOX') OR (PART.CONTAINER =
'SM PACK') OR (PART.CONTAINER ='SM PKG') 
