#TPCH7:ver1.0

SELECT N1.NAME, N2.NAME, EXTRACT_YEAR(LINEITEM.SHIPDATE), SUM(LINEITEM.EXTENDEDPRICE * (1.0-LINEITEM.DISCOUNT))
FROM SUPPLIER
inner join LINEITEM on SUPPLIER.SUPPKEY = LINEITEM.SUPPKEY
inner join NATION N1 on SUPPLIER.NATIONKEY = N1.NATIONKEY
inner join ORDERS on ORDERS.ORDERKEY = LINEITEM.ORDERKEY
inner join CUSTOMER on CUSTOMER.CUSTKEY = ORDERS.CUSTKEY
inner join NATION N2 on CUSTOMER.NATIONKEY = N2.NATIONKEY
WHERE ((N1.NAME = 'FRANCE' AND N2.NAME = 'GERMANY') OR (N1.NAME = 'GERMANY' AND N2.NAME = 'FRANCE'))
AND LINEITEM.SHIPDATE >= {d '1995-01-01'} AND LINEITEM.SHIPDATE <= {d '1996-12-31'}
